// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "../../components/Game/Game.bs.js";
import * as React from "react";
import * as GamePageModuleCss from "./GamePage.module.css";

var styles = GamePageModuleCss;

function GamePage(props) {
  return React.createElement(Game.make, {});
}

var make = GamePage;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
