// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as MainPageModuleCss from "./MainPage.module.css";

var styles = MainPageModuleCss;

function MainPage(props) {
  var children = props.children;
  var handleStartGameLinkClick = function (e) {
    e.preventDefault();
    RescriptReactRouter.push("game");
  };
  return React.createElement("div", {
              className: styles.menuContainer
            }, React.createElement("div", {
                  className: styles.linkList
                }, React.createElement("a", {
                      className: styles.gameMenuLink,
                      href: "pages/game/game.html"
                    }, "Начать игру"), React.createElement("a", {
                      className: styles.gameMenuLink,
                      href: "pages/levels/levels.html"
                    }, "Выбрать уровень"), React.createElement("a", {
                      className: styles.gameMenuLink,
                      href: "/cow-game/game",
                      onClick: handleStartGameLinkClick
                    }, "Начать игру(react-demo)"), React.createElement("a", {
                      className: styles.gameMenuLink,
                      href: "pages/phaser/phaser.html"
                    }, "Начать игру(phaser)"), children !== undefined ? Caml_option.valFromOption(children) : null));
}

var make = MainPage;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
