// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Game(props) {
  return React.createElement("main", undefined, React.createElement("p", undefined, "Страница игры"));
}

var make = Game;

export {
  make ,
}
/* react Not a pure module */
