// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Config from "../../Config.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as GameMenuModuleCss from "./GameMenu.module.css";

var styles = GameMenuModuleCss;

function GameMenu(props) {
  var table = Belt_Array.make(Config.gameConfig.arrowsTable.height, Belt_Array.makeBy(Config.gameConfig.arrowsTable.width, (function (i) {
              return React.createElement("td", {
                          key: String(i),
                          className: styles.cell
                        });
            })));
  return React.createElement("aside", {
              className: Belt_Option.mapWithDefault(props.className, styles.container, (function (className) {
                      return "" + className + " " + styles.container + "";
                    }))
            }, React.createElement("table", {
                  className: styles.menuTable
                }, React.createElement("tbody", undefined, Belt_Array.mapWithIndex(table, (function (i, row) {
                            return React.createElement("tr", {
                                        key: String(i)
                                      }, row);
                          })))));
}

var make = GameMenu;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
