// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./pages/Game.bs.js";
import * as React from "react";
import * as AppModuleCss from "./App.module.css";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var styles = AppModuleCss;

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var tmp;
  tmp = match ? (
      match.hd === "game" && !match.tl ? React.createElement(Game.make, {}) : React.createElement("div", undefined, "page not found")
    ) : React.createElement("div", undefined, "main page");
  return React.createElement("div", undefined, React.createElement("a", {
                  className: styles["game-menu-link"],
                  href: "pages/game/game.html"
                }, "Начать игру"), React.createElement("a", {
                  className: styles["game-menu-link"],
                  href: "pages/levels/levels.html"
                }, "Выбрать уровень"), React.createElement("a", {
                  className: "game-menu-link",
                  href: "/game"
                }, "Начать игру(react)"), tmp);
}

var make = App;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
