// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./pages/Game.bs.js";
import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var tmp;
  tmp = match ? (
      match.hd === "game" && !match.tl ? React.createElement(Game.make, {}) : React.createElement("div", undefined, "page not found")
    ) : React.createElement("div", undefined, "main page");
  return React.createElement("div", undefined, React.createElement("a", {
                  className: "game-menu-link",
                  href: "/game"
                }, "Начать игру"), tmp);
}

var make = App;

export {
  make ,
  
}
/* Game Not a pure module */
