// Generated by ReScript, PLEASE EDIT WITH CARE


var gameConfig = {
  map: {
    width: 20,
    height: 14
  },
  arrowsTable: {
    width: 3,
    height: 7
  },
  loopTime: 250
};

export {
  gameConfig ,
  
}
/* No side effect */
