name: Project build

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Staring Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint JS
        run: npm run lint

      - name: Lint CSS
        run: npm run lint:css

      - name: Build project
        run: npm run build
